# Site settings
title: Student
email: hiya@email.com
url: http://127.0.0.1:4000/
description: "I am a student"
baseurl: 'rgrantwylie_elements_website'

# Footer settings
footer: Student | Copyright 2017 

# Social networks usernames 
social:
  - title: Instagram
    url: https://#
  - title: Github
    url: https://#
  - title: Twitter
    url: https://#

# Build settings
markdown: kramdown
permalink: pretty